const RATIO_DIST = 10**(-1);
const RADIO_PERIODE = 10**(-3);

const RATIO_RAYON = 10**(-4);

const SOLEIL_RAYON = 696340 * RATIO_RAYON / 10; // millions de km / 10
const SOLEIL_DIST = 0;
const SOLEIL_PERIODE = 0;
const SOLEIL_COLOR = "#fff000";

const MERCURE_PERIODE = 88 * RADIO_PERIODE
const MERCURE_DIST = 58 * RATIO_DIST; // Millions de km
const MERCURE_RAYON = 2439 * RATIO_RAYON; // Millions de km
const MERCURE_COLOR = "#00ff00";

const VENUS_PERIODE = 243 * RADIO_PERIODE
const VENUS_DIST = 108 * RATIO_DIST;
const VENUS_RAYON = 6051 * RATIO_RAYON; // Millions de km
const VENUS_COLOR = "#00ff00";

const TERRE_PERIODE = 365 * RADIO_PERIODE
const TERRE_DIST = 149 * RATIO_DIST;
const TERRE_RAYON = 6371 * RATIO_RAYON; // Millions de km
const TERRE_COLOR = "#0000ff";

const LUNE_PERIODE = 29 * RADIO_PERIODE
const LUNE_DIST_TERR = 384400 * RATIO_DIST * 10**(-6); // millions de km
const LUNE_RAYON = 1737 * RATIO_RAYON; // Millions de km
const LUNE_COLOR = "#f5f5f5";

const MARS_PERIODE = 186 * RADIO_PERIODE
const MARS_DIST = 228 * RATIO_DIST;
const MARS_RAYON = 3389 * RATIO_RAYON; // Millions de km
const MARS_COLOR = "#ff0000";

const JUPITER_PERIODE = 11*365 * RADIO_PERIODE
const JUPITER_DIST = 778 * RATIO_DIST;
const JUPITER_RAYON = 69911 * RATIO_RAYON; // Millions de km
const JUPITER_COLOR = "#00ff00";

const SATURNE_PERIODE = 29.5*365 * RADIO_PERIODE
const SATURNE_DIST = 1430 * RATIO_DIST;
const SATURNE_RAYON = 58232 * RATIO_RAYON; // Millions de km
const SATURE_COLOR = "#00ff00";

const URANUS_PERIODE = 84*365 * RADIO_PERIODE
const URANUS_DIST = 2800 * RATIO_DIST;
const URANUS_RAYON = 25362 * RATIO_RAYON; // Millions de km
const URANUS_COLOR = "#00ff00";

const NEPTUNE_PERIODE = 165*365 * RADIO_PERIODE
const NEPTUNE_DIST = 4504 * RATIO_DIST;
const NEPTUNE_RAYON = 24622 * RATIO_RAYON; // Millions de km
const NEPTUNE_COLOR = "#00ff00";

const RAYONS = [
    SOLEIL_RAYON,
    MERCURE_RAYON,
    VENUS_RAYON,
    TERRE_RAYON,
    LUNE_RAYON,
    MARS_RAYON,
    JUPITER_RAYON,
    SATURNE_RAYON,
    URANUS_RAYON,
    NEPTUNE_RAYON,
];

const DISTANCES = [
    SOLEIL_DIST,
    MERCURE_DIST,
    VENUS_DIST,
    TERRE_DIST,
    LUNE_DIST_TERR,
    MARS_DIST,
    JUPITER_DIST,
    SATURNE_DIST,
    URANUS_DIST,
    NEPTUNE_DIST,
];

const PERIODES = [
    SOLEIL_PERIODE,
    MERCURE_PERIODE,
    VENUS_PERIODE,
    TERRE_PERIODE,
    LUNE_PERIODE,
    MARS_PERIODE,
    JUPITER_PERIODE,
    SATURNE_PERIODE,
    URANUS_PERIODE,
    NEPTUNE_PERIODE,
];

const COLORS = [
    SOLEIL_COLOR,
    MERCURE_COLOR,
    VENUS_COLOR,
    TERRE_COLOR,
    LUNE_COLOR,
    MARS_COLOR,
    JUPITER_COLOR,
    SATURE_COLOR,
    URANUS_COLOR,
    NEPTUNE_COLOR
]

export { 
    PERIODES,
    DISTANCES,
    RAYONS,
    COLORS,
}